version: '3.8'
services:
  app:
    build: .
    container_name: app-service
    depends_on:
      - db
    ports:
      - "5000:5000"
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
